import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import ConditionalFooter from "./components/ConditionalFooter";
import LoginCard from "./components/LoginCard";
import JoinCard1 from "./components/JoinCard1";
import JoinCard2 from "./components/JoinCard2";
import JoinCard3 from "./components/JoinCard3";
import JoinCard4 from "./components/JoinCard4";
import JoinCard5 from "./components/JoinCard5";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* <LoginCard /> */}
        {/* <JoinCard1 /> */}
        {/* <JoinCard2 /> */}
        {/* <JoinCard3 /> */}
        {/* <JoinCard4 /> */}
        <JoinCard5 />
        <Header />
        {children}
        <ConditionalFooter />
      </body>
    </html>
  );
}
